// Generated by tools/tilesetcap/tilesetcap.py from the tileset and layout data. Do not edit.

#if !IS_FRLG

extern const struct Tileset gTileset_BattleArena;
extern const struct Tileset gTileset_BattleDome;
extern const struct Tileset gTileset_BattleFactory;
extern const struct Tileset gTileset_BattleFrontier;
extern const struct Tileset gTileset_BattleFrontierOutsideEast;
extern const struct Tileset gTileset_BattleFrontierOutsideWest;
extern const struct Tileset gTileset_BattleFrontierRankingHall;
extern const struct Tileset gTileset_BattlePalace;
extern const struct Tileset gTileset_BattlePike;
extern const struct Tileset gTileset_BattlePyramid;
extern const struct Tileset gTileset_BattleTent;
extern const struct Tileset gTileset_BikeShop;
extern const struct Tileset gTileset_BrendansMaysHouse;
extern const struct Tileset gTileset_Building;
extern const struct Tileset gTileset_CableClub;
extern const struct Tileset gTileset_Cave;
extern const struct Tileset gTileset_Contest;
extern const struct Tileset gTileset_Dewford;
extern const struct Tileset gTileset_DewfordGym;
extern const struct Tileset gTileset_EliteFour;
extern const struct Tileset gTileset_EverGrande;
extern const struct Tileset gTileset_Facility;
extern const struct Tileset gTileset_Fallarbor;
extern const struct Tileset gTileset_Fortree;
extern const struct Tileset gTileset_FortreeGym;
extern const struct Tileset gTileset_General;
extern const struct Tileset gTileset_GenericBuilding;
extern const struct Tileset gTileset_InsideOfTruck;
extern const struct Tileset gTileset_InsideShip;
extern const struct Tileset gTileset_IslandHarbor;
extern const struct Tileset gTileset_Lab;
extern const struct Tileset gTileset_Lavaridge;
extern const struct Tileset gTileset_LavaridgeGym;
extern const struct Tileset gTileset_Lilycove;
extern const struct Tileset gTileset_LilycoveMuseum;
extern const struct Tileset gTileset_Mauville;
extern const struct Tileset gTileset_MauvilleGameCorner;
extern const struct Tileset gTileset_MauvilleGym;
extern const struct Tileset gTileset_MeteorFalls;
extern const struct Tileset gTileset_MirageTower;
extern const struct Tileset gTileset_Mossdeep;
extern const struct Tileset gTileset_MossdeepGameCorner;
extern const struct Tileset gTileset_MossdeepGym;
extern const struct Tileset gTileset_MysteryEventsHouse;
extern const struct Tileset gTileset_NavelRock;
extern const struct Tileset gTileset_OceanicMuseum;
extern const struct Tileset gTileset_Pacifidlog;
extern const struct Tileset gTileset_Petalburg;
extern const struct Tileset gTileset_PetalburgGym;
extern const struct Tileset gTileset_PokemonCenter;
extern const struct Tileset gTileset_PokemonDayCare;
extern const struct Tileset gTileset_PokemonFanClub;
extern const struct Tileset gTileset_PokemonSchool;
extern const struct Tileset gTileset_PrettyPetalFlowerShop;
extern const struct Tileset gTileset_Rustboro;
extern const struct Tileset gTileset_RustboroGym;
extern const struct Tileset gTileset_RusturfTunnel;
extern const struct Tileset gTileset_SeashoreHouse;
extern const struct Tileset gTileset_SecretBase;
extern const struct Tileset gTileset_SecretBaseBlueCave;
extern const struct Tileset gTileset_SecretBaseBrownCave;
extern const struct Tileset gTileset_SecretBaseRedCave;
extern const struct Tileset gTileset_SecretBaseShrub;
extern const struct Tileset gTileset_SecretBaseTree;
extern const struct Tileset gTileset_SecretBaseYellowCave;
extern const struct Tileset gTileset_Shop;
extern const struct Tileset gTileset_Slateport;
extern const struct Tileset gTileset_Sootopolis;
extern const struct Tileset gTileset_SootopolisGym;
extern const struct Tileset gTileset_TrainerHill;
extern const struct Tileset gTileset_TrickHousePuzzle;
extern const struct Tileset gTileset_Underwater;
extern const struct Tileset gTileset_UnionRoom;
extern const struct Tileset gTileset_Unused1;
extern const struct Tileset gTileset_Unused2;

static const u32 sTileCacheRawTiles_General[] = INCGFX_U32("data/tilesets/primary/general/tiles.png", ".4bpp");
static const u32 sTileCacheRawTiles_Petalburg[] = INCGFX_U32("data/tilesets/secondary/petalburg/tiles.png", ".4bpp");
static const u8 sMetatileTileExt_Petalburg[] = INCBIN_U8("data/tilesets/secondary/petalburg/metatile_tiles_ext.bin");

const struct TilesetCapacityInfo gTilesetCapacityInfo[] =
{
    {
        .tileset = &gTileset_BattleArena,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 272,
        .numMetatiles = 177,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_BattleDome,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 464,
        .numMetatiles = 427,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_BattleFactory,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 432,
        .numMetatiles = 354,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_BattleFrontier,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 320,
        .numMetatiles = 509,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_BattleFrontierOutsideEast,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 512,
        .numMetatiles = 510,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_BattleFrontierOutsideWest,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 512,
        .numMetatiles = 510,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_BattleFrontierRankingHall,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 144,
        .numMetatiles = 94,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_BattlePalace,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 144,
        .numMetatiles = 174,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_BattlePike,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 384,
        .numMetatiles = 347,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_BattlePyramid,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 464,
        .numMetatiles = 221,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_BattleTent,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 256,
        .numMetatiles = 269,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_BikeShop,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 512,
        .numMetatiles = 248,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_BrendansMaysHouse,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 480,
        .numMetatiles = 196,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_Building,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 512,
        .numMetatiles = 8,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_CableClub,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 512,
        .numMetatiles = 256,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_Cave,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 432,
        .numMetatiles = 414,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_Contest,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 432,
        .numMetatiles = 233,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_Dewford,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 512,
        .numMetatiles = 379,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_DewfordGym,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 64,
        .numMetatiles = 69,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_EliteFour,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 512,
        .numMetatiles = 332,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_EverGrande,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 320,
        .numMetatiles = 168,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_Facility,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 512,
        .numMetatiles = 511,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_Fallarbor,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 448,
        .numMetatiles = 367,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_Fortree,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 496,
        .numMetatiles = 280,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_FortreeGym,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 64,
        .numMetatiles = 80,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_General,
        .rawTiles = sTileCacheRawTiles_General,
        .tileExt = NULL,
        .numTiles = 512,
        .numMetatiles = 512,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_GenericBuilding,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 512,
        .numMetatiles = 512,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_InsideOfTruck,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 64,
        .numMetatiles = 38,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_InsideShip,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 352,
        .numMetatiles = 252,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_IslandHarbor,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 512,
        .numMetatiles = 470,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_Lab,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 512,
        .numMetatiles = 158,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_Lavaridge,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 464,
        .numMetatiles = 441,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_LavaridgeGym,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 64,
        .numMetatiles = 61,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_Lilycove,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 432,
        .numMetatiles = 351,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_LilycoveMuseum,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 432,
        .numMetatiles = 143,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_Mauville,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 512,
        .numMetatiles = 510,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_MauvilleGameCorner,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 480,
        .numMetatiles = 96,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_MauvilleGym,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 160,
        .numMetatiles = 117,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_MeteorFalls,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 464,
        .numMetatiles = 159,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_MirageTower,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 432,
        .numMetatiles = 414,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_Mossdeep,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 512,
        .numMetatiles = 454,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_MossdeepGameCorner,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 96,
        .numMetatiles = 53,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_MossdeepGym,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 96,
        .numMetatiles = 117,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_MysteryEventsHouse,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 512,
        .numMetatiles = 67,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_NavelRock,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 432,
        .numMetatiles = 451,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_OceanicMuseum,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 320,
        .numMetatiles = 122,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_Pacifidlog,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 512,
        .numMetatiles = 203,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_Petalburg,
        .rawTiles = sTileCacheRawTiles_Petalburg,
        .tileExt = sMetatileTileExt_Petalburg,
        .numTiles = 160,
        .numMetatiles = 144,
        .streamed = TRUE,
    },
    {
        .tileset = &gTileset_PetalburgGym,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 160,
        .numMetatiles = 224,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_PokemonCenter,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 480,
        .numMetatiles = 232,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_PokemonDayCare,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 368,
        .numMetatiles = 68,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_PokemonFanClub,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 320,
        .numMetatiles = 104,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_PokemonSchool,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 288,
        .numMetatiles = 58,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_PrettyPetalFlowerShop,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 352,
        .numMetatiles = 72,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_Rustboro,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 512,
        .numMetatiles = 350,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_RustboroGym,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 64,
        .numMetatiles = 56,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_RusturfTunnel,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 144,
        .numMetatiles = 83,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_SeashoreHouse,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 320,
        .numMetatiles = 56,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_SecretBase,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 512,
        .numMetatiles = 2,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_SecretBaseBlueCave,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 0,
        .numMetatiles = 324,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_SecretBaseBrownCave,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 0,
        .numMetatiles = 324,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_SecretBaseRedCave,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 0,
        .numMetatiles = 324,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_SecretBaseShrub,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 0,
        .numMetatiles = 324,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_SecretBaseTree,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 0,
        .numMetatiles = 324,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_SecretBaseYellowCave,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 0,
        .numMetatiles = 324,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_Shop,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 512,
        .numMetatiles = 289,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_Slateport,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 512,
        .numMetatiles = 406,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_Sootopolis,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 336,
        .numMetatiles = 254,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_SootopolisGym,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 496,
        .numMetatiles = 122,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_TrainerHill,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 384,
        .numMetatiles = 486,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_TrickHousePuzzle,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 304,
        .numMetatiles = 189,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_Underwater,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 512,
        .numMetatiles = 236,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_UnionRoom,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 208,
        .numMetatiles = 49,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_Unused1,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 32,
        .numMetatiles = 2,
        .streamed = FALSE,
    },
    {
        .tileset = &gTileset_Unused2,
        .rawTiles = NULL,
        .tileExt = NULL,
        .numTiles = 160,
        .numMetatiles = 58,
        .streamed = FALSE,
    },
};

#else

const struct TilesetCapacityInfo gTilesetCapacityInfo[] = {{0}};

#endif // !IS_FRLG

const u32 gTilesetCapacityInfoCount = ARRAY_COUNT(gTilesetCapacityInfo);
